name: Auto Patch Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  auto-patch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Run make patch
      run: |
        chmod +x scripts/bump-version.sh
        make patch