name: Release on Tag Push

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    with:
      tag: ${{ github.ref_name }}
